### ISSUE TITLE
When I confirm the login on steam, a 302 error occurs on the network request

### ISSUE THREAD

**Issue by m1em1e** [FerroEduardo/spring-steam-login#1]
The error occurred in the SteamService.java:67, and I checked my web request in my browser and found a 302 error as well as Location is 
<img width="433" alt="屏幕截图 2024-06-06 164816" src="https://github.com/FerroEduardo/spring-steam-login/assets/169110426/60bd9df4-7ec6-49ee-aa87-f78e39813159">

**Comment by FerroEduardo** [comment]
I was unable to reproduce. Did you set `localhost` as the domain name when the Steam API Key was created?

**Comment by m1em1e** [comment]
Oh, I got API Key  wrong. The API key I used is bound to a different domain name.
